# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];
  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/5e8e5a14-3651-4da1-a2d9-f5d0f68e5438";

  swapDevices = [{device = "/dev/disk/by-uuid/7aaf6484-ee35-435a-aa13-0b5e92f8294d";}];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8A4A-F279";
    fsType = "vfat";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b7f94a49-6c05-4ad5-b432-70e9c6c3c53e";
    fsType = "btrfs";
    options = ["subvol=root"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/b7f94a49-6c05-4ad5-b432-70e9c6c3c53e";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/b7f94a49-6c05-4ad5-b432-70e9c6c3c53e";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/b7f94a49-6c05-4ad5-b432-70e9c6c3c53e";
    fsType = "btrfs";
    options = ["subvol=data"];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
